services:
  postgres:
    image: dockerpull.pw/library/postgres:15
    container_name: fly-print-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "0.0.0.0:${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fly-print-network

  redis:
    image: dockerpull.pw/library/redis:7-alpine
    container_name: fly-print-redis
    ports:
      - "0.0.0.0:${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - fly-print-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - GOPROXY=https://goproxy.cn,direct
    container_name: fly-print-api
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - postgres
      - redis
    networks:
      - fly-print-network

  admin-console-builder:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: fly-print-admin-builder
    volumes:
      - admin_build:/app/build
    restart: "no"
    networks:
      - fly-print-network

  nginx:
    image: dockerpull.pw/library/nginx:alpine
    container_name: fly-print-nginx
    ports:
      - "${ADMIN_PORT}:80"
      - "${API_PORT}:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - admin_build:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - fly-print-network

volumes:
  postgres_data:
  redis_data:
  admin_build:

networks:
  fly-print-network:
    driver: bridge
