app:
  name: "fly-print-cloud"
  version: "0.1.0"
  environment: "development"
  debug: true

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "fly_print_cloud"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "fly-print-cloud-secret-key-change-in-production"
  expiration_time: 24  # 小时
  refresh_time: 168    # 小时 (7天)

server:
  host: "0.0.0.0"
  port: 8080